### ISSUE TITLE
Block was not detected to have been accepted

### ISSUE THREAD

**Issue by sigwo** [sigwo/node-merged-portal#3]
``` bash
BLOCK found by sigwo on SYS, VALUE: 0
[FST] Message: Submitted block was rejected by the undefined network! Check its log for more information
[FST] Message: Block was not detect to have been accepted byundefined network: ad01de4a6fa81fe01b9768b60b249ab7e65a204a3274442566614b712245dddd
BLOCK found by sigwo on SYS, VALUE: 0

/home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:602
                throw err;
                      ^
TypeError: Cannot call method 'toString' of undefined
    at /home/ironman/unomp/node-merged-portal/db.js:77:36
    at /home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:1210:13
    at try_callback (/home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_reply (/home/ironman/unomp/node-merged-portal/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/home/ironman/unomp/node-merged-portal/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/home/ironman/unomp/node-merged-portal/node_modules/redis/index.js:102:14)
```

Pool and site seems to die a slow death afterwards.

**Comment by sigwo** [comment]
Making progress with PR #8 

``` bash
[DGC] Message: Submitted block was rejected by the Syscoin network! Check its log for more information
[DGC] Message: Block was not detected to have been accepted by Syscoin network: c575e37ed908cabd48cddd39e9c4c6d41756496ffcf170e307eb9cde1ecd54c3
[DGC] Message: Some error occured: {"code":-1,"message":"value is type null, expected str"}
```
