### ISSUE TITLE
Cannot read property 'chainid' of undefined

### ISSUE THREAD

**Issue by sigwo** [sigwo/node-merged-portal#7]
``` bash
/root/node-merged-portal/node_modules/merged-pooler/lib/jobManager.js:122
                var pos = util.getAuxMerklePosition(auxData[i].chainid, size);
                                                              ^
TypeError: Cannot read property 'chainid' of undefined
    at buildMerkleTree (/root/node-merged-portal/node_modules/merged-pooler/lib/jobManager.js:122:63)
    at JobManager.processTemplate (/root/node-merged-portal/node_modules/merged-pooler/lib/jobManager.js:186:29)
    at /root/node-merged-portal/node_modules/merged-pooler/lib/pool.js:695:69
    at itemFinished (/root/node-merged-portal/node_modules/merged-pooler/lib/daemon.js:156:36)
    at /root/node-merged-portal/node_modules/merged-pooler/lib/daemon.js:169:17
    at parseJson (/root/node-merged-portal/node_modules/merged-pooler/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/node-merged-portal/node_modules/merged-pooler/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by sigwo** [comment]
this is an error if you do not have an auxcoin set properly in coins/ or in pools/*.json. I cannot reproduce unless that happens.
